parameters:
- name: environmentName
  type: string
- name: backendRG
  type: string
- name: backendSA
  type: string
- name: backendKey
  type: string
- name: azureServiceConnection
  type: string
- name: approvalEmail
  type: string

jobs:
- job: TerraformInit
  displayName: 'Initialize: ${{ parameters.environmentName }}'
  steps:
  - checkout: self

  - task: TerraformInstaller@0
    inputs:
      terraformVersion: '1.5.5'

  - task: TerraformTaskV4@4
    displayName: Terraform Init
    inputs:
      provider: 'azurerm'
      backendServiceArm: ${{ parameters.azureServiceConnection }}
      backendAzureRmResourceGroupName: ${{ parameters.backendRG }}
      backendAzureRmStorageAccountName: ${{ parameters.backendSA }}
      backendAzureRmContainerName: 'tfstate'
      backendAzureRmKey: ${{ parameters.backendKey }}
      command: 'init'
      workingDirectory: 'terraform'

  - task: TerraformTaskV4@4
    displayName: Terraform Validate
    inputs:
      provider: 'azurerm'
      command: 'validate'
      workingDirectory: 'terraform'

- job: TerraformPlan
  displayName: 'Plan: ${{ parameters.environmentName }}'
  dependsOn: TerraformInit
  steps:
  - checkout: self

  - task: TerraformTaskV4@4
    displayName: Terraform Plan
    inputs:
      provider: 'azurerm'
      command: 'plan'
      environmentServiceNameAzureRM: ${{ parameters.azureServiceConnection }}
      workingDirectory: 'terraform'

- job: waitForValidation
  displayName: 'Wait for external validation'
  pool: server
  timeoutInMinutes: 4320
  dependsOn: TerraformPlan
  steps:
  - task: ManualValidation@0
