trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.5.5'
  azureServiceConnection: 'terraform_consumpetion_logicapp1'
  backendResourceGroup: 'skink-rg'
  backendStorageAccount: 'skinktfstate'
  backendContainer: 'tfstate'
  backendKey: 'terraform.tfstate'

stages:
- stage: Initialization
  jobs:
  - job: TerraformRun
    steps:
    - checkout: self

    - task: TerraformInstaller@0
      inputs:
        terraformVersion: $(terraformVersion)

    - task: TerraformTaskV4@4
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: $(azureServiceConnection)
        backendAzureRmResourceGroupName: $(backendResourceGroup)
        backendAzureRmStorageAccountName: $(backendStorageAccount)
        backendAzureRmContainerName: $(backendContainer)
        backendAzureRmKey: $(backendKey)
        workingDirectory: 'terraform'

    - task: TerraformTaskV4@4
      displayName: Terraform Validate
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: 'terraform'

    - task: TerraformTaskV4@4
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: $(azureServiceConnection)
        workingDirectory: 'terraform'

    - task: TerraformTaskV4@4
      displayName: Terraform Apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        commandOptions: '--auto-approve'
        environmentServiceNameAzureRM: $(azureServiceConnection)
        workingDirectory: 'terraform'
``
